import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.*;

/**
 * Class: AdminController
 * This class represents the controller of the Admin window which it is in admin view.
 * It takes care the of actions when buttons are displays are pressed in the window.
 */
public class AdminController implements ActionListener {
    private AdminModel model;
    private AdminView view;

    /**
     * Constructs an AdminController with the specified model and view.
     *
     * @param m The AdminModel instance.
     * @param v The AdminView instance.
     */
    public AdminController(AdminModel m, AdminView v) {
        this.model = m;
        this.view = v;
        view.setActionListener(this);
    }

    /**
     * Handles action events triggered by user interactions in the AdminView
     * (e.g. clicking buttons)
     *
     * @param e The ActionEvent generated by a user action.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        switch (e.getActionCommand()) {
            // ------------------ Manage Database Panel component ------------------
            case "MANAGE DATABASE":
                view.getCardLayout().show(view.getMainPanel(), "MANAGE_DATABASE_MENU");
                break;
            case "Create User":
                view.getCardLayout().show(view.getMainPanel(), "USER_CREATE");
                break;
            case "Log a New Dish":
                System.out.println("Log a New Dish clicked!");
                break;

            // ------------------ Register/Create User Panel component ------------------
            case "REGISTER USER":
                ArrayList<String> input = view.getRegistrationInput();
                String username = input.get(0);
                String email = input.get(1);
                try {
                    // Check for empty fields first
                    if (username.isEmpty() || email.isEmpty()) {
                        JOptionPane.showMessageDialog(view,
                                "Username and/or Email cannot be empty.",
                                "Input Error",
                                JOptionPane.WARNING_MESSAGE);
                        return; // Stop processing
                    }

                    boolean isSuccess = model.registerNewUser(username, email);

                    if (isSuccess) {
                        // 3. Show a success message
                        JOptionPane.showMessageDialog(view,
                                "User registered successfully!",
                                "Success",
                                JOptionPane.INFORMATION_MESSAGE);

                        // 4. Go back to the manage database menu
                        view.getCardLayout().show(view.getMainPanel(), "MANAGE_DATABASE_MENU");

                    } else {
                        // 3. Show an error message (e.g., user already exists)
                        JOptionPane.showMessageDialog(view,
                                "Error: Could not register user.\nCheck console for details (e.g., duplicate entry).",
                                "Registration Failed",
                                JOptionPane.ERROR_MESSAGE);
                    }

                } catch (Exception ex) {
                    // Catch any other unexpected errors
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(view,
                            "An unexpected error occurred: " + ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
               // view.getCardLayout().show(view.getMainPanel(), "GENERATE_REPORTS_MENU");
                break;

            // ------------------ Generate Reports panel component ------------------
            case "GENERATE REPORTS":
                updateView();
                view.getCardLayout().show(view.getMainPanel(), "GENERATE_REPORTS_MENU");
                break;
            case "New User Registration":
                // 1. Get the list of all users from the model
                ArrayList<UserData> users = model.getAllUsers();

                // 2. Pass the list to the view to update its *report* table
                view.updateUserReportTable(users);

                // 3. Show the (now populated) user *report* panel
                view.getCardLayout().show(view.getMainPanel(), "USER_REPORT_PANEL");
                break;
            case "User Referral Impact":
                System.out.println(2);
                break;
            case "Popular Menu Items":
                System.out.println(3);
                break;
            case "Food, Ratings and Feedback":
                ArrayList<String> restaurantNames = model.getRestaurantNames();
                view.populateFeedbackRestaurantComboBox(restaurantNames);
                view.updateFeedbackReportPanel(null);
                view.getCardLayout().show(view.getMainPanel(), "FEEDBACK_REPORT_PANEL");
                break;
            case "Fetch Feedback Report":
                String restaurant = view.getFeedbackSelectedRestaurant();
                if (restaurant.equals("[Select One]")) {
                    JOptionPane.showMessageDialog(view, "Please select a restaurant.", "Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                RestaurantFeedbackReport data = model.getFeedbackReport(restaurant);
                view.updateFeedbackReportPanel(data);
                break;

            case "Go Back Feedback Report":
                view.getCardLayout().show(view.getMainPanel(), "GENERATE_REPORTS_MENU");
                break;
            case "Revenue and Transaction":
                ArrayList<RestaurantRevenueData> reportData = model.getRestaurantRevenueReport();
                view.updateRevenueReportTable(reportData);
                view.getCardLayout().show(view.getMainPanel(), "REVENUE_REPORT_PANEL");
                break;

            // ------------------ BASIC NAVIGATION BUTTONS ------------------
            case "GO BACK", "GO BACK GENERATE REPORTS":
                view.getCardLayout().show(view.getMainPanel(), "MAIN_MENU");
                break;
            case "GO BACK USER REG":
                view.getCardLayout().show(view.getMainPanel(), "MANAGE_DATABASE_MENU");
                break;
            case "GO BACK USER REPORT":
                view.getCardLayout().show(view.getMainPanel(), "GENERATE_REPORTS_MENU");
                break;
            case "Go Back Revenue Report":
                view.getCardLayout().show(view.getMainPanel(), "GENERATE_REPORTS_MENU");
                break;
            case "GO BACK TO MAIN":
                view.dispose();
                model.getMenuController().showMenuView();
                break;
        }
    }

    /**
     * Refreshes all panels, re-attaches listeners, and updates displayed data.
     * Called after any update to the model or view state to ensure UI consistency.
     */
    private void updateView() {
        view.refreshPanels();
        view.setActionListener(this);
    }
}