import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Class: AdminController
 * This class represents the controller of the Admin window which it is in admin view.
 * It takes care the of actions when buttons are displays are pressed in the window.
 */
public class AdminController implements ActionListener {
    private AdminModel model;
    private AdminView view;

    /**
     * Constructs an AdminController with the specified model and view.
     *
     * @param m The AdminModel instance.
     * @param v The AdminView instance.
     */
    public AdminController(AdminModel m, AdminView v) {
        this.model = m;
        this.view = v;

        view.setActionListener(this);
    }

    /**
     * Handles action events triggered by user interactions in the AdminView
     * (e.g. clicking buttons)
     *
     * @param e The ActionEvent generated by a user action.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        switch (e.getActionCommand()) {
            case "SIMULATE":
                view.getCardLayout().show(view.getMainPanel(), "SIMULATE_VIEW");
                break;
            case "DASHBOARD":
                updateView();
                view.getCardLayout().show(view.getMainPanel(), "DASHBOARD_MENU");
                break;
            case "GO BACK", "GO BACK DASHBOARD":
                view.getCardLayout().show(view.getMainPanel(), "MAIN_MENU");
                break;
            case "GO BACK TO MAIN":
                view.dispose();
                model.getMenuController().showMenuView();
                break;
        }
    }

    /**
     * Refreshes all panels, re-attaches listeners, and updates displayed data.
     * Called after any update to the model or view state to ensure UI consistency.
     */
    private void updateView() {
        view.refreshPanels();
        view.setActionListener(this);
    }
}