import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Class: AdminController
 * This class represents the controller of the Admin window which it is in admin view.
 * It takes care the of actions when buttons are displays are pressed in the window.
 */
public class AdminController implements ActionListener {
    private AdminModel model;
    private AdminView view;

    /**
     * Constructs an AdminController with the specified model and view.
     *
     * @param m The AdminModel instance.
     * @param v The AdminView instance.
     */
    public AdminController(AdminModel m, AdminView v) {
        this.model = m;
        this.view = v;

        view.setActionListener(this);
    }

    /**
     * Handles action events triggered by user interactions in the AdminView
     * (e.g. clicking buttons)
     *
     * @param e The ActionEvent generated by a user action.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        switch (e.getActionCommand()) {
            // MANAGE DATABASE
            case "MANAGE DATABASE":
                view.getCardLayout().show(view.getMainPanel(), "MANAGE_DATABASE_MENU");
                break;
            case "Read User Feedback":
                System.out.println("This this supposed to be for the customer (1)");
                break;
            case "Reserve Order":
                System.out.println("Change this to make a new promo instead for admin");
                break;
            case "Log a New Dish":
                System.out.println("Log a New Dish clicked!");
                break;
            case "Personalize Meal Recommendations":
                System.out.println("This this supposed to be for the customer (2)");
                break;

            // GENERATE REPORTS
            case "GENERATE REPORTS":
                updateView();
                view.getCardLayout().show(view.getMainPanel(), "GENERATE_REPORTS_MENU");
                break;
            case "New User Registration":
                System.out.println(1);
                break;
            case "User Referral Impact":
                System.out.println(2);
                break;
            case "Popular Menu Items":
                System.out.println(3);
                break;
            case "Food, Ratings and Feedback":
                System.out.println(4);
                break;
            case "Revenue and Transaction":
                System.out.println(5);
                break;

            // BASIC NAVIGATION BUTTONS
            case "GO BACK", "GO BACK GENERATE REPORTS":
                view.getCardLayout().show(view.getMainPanel(), "MAIN_MENU");
                break;
            case "GO BACK TO MAIN":
                view.dispose();
                model.getMenuController().showMenuView();
                break;
        }
    }

    /**
     * Refreshes all panels, re-attaches listeners, and updates displayed data.
     * Called after any update to the model or view state to ensure UI consistency.
     */
    private void updateView() {
        view.refreshPanels();
        view.setActionListener(this);
    }
}