import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * Class: CustomerController
 * This class represents the controller of the Customer window.
 * It takes care the of actions when buttons are displays are pressed in the window.
 * It provides signals for the customer view and model on the sequence of
 * functions that will be done in the program.
 */
public class CustomerController implements ActionListener {
    private CustomerModel model;
    private CustomerView view;

    /**
     * Constructs a CustomerController with the given model and view.
     * Registers itself as the ActionListener for view events.
     *
     * @param m the CustomerModel to update
     * @param v the CustomerView to control
     */
    public CustomerController(CustomerModel m, CustomerView v) {
        this.model = m;
        this.view = v;

        view.setActionListener(this);
        view.setVisible(true);
    }

    /**
     * Handles all button click events from the view.
     *
     * @param e The ActionEvent generated by a user action.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        switch (e.getActionCommand()) {
            // SIGN IN
            case "SIGN IN":
                ArrayList<String> signInInput = view.getSignInInput();
                System.out.printf("name: %s%n", signInInput.get(0));
                System.out.printf("email: %s%n", signInInput.get(1));
                view.getCardLayout().show(view.getMainPanel(), "MAIN_MENU");
                break;

            // BASIC NAVIGATION BUTTONS
            case "GO BACK":
                view.getCardLayout().show(view.getMainPanel(), "START_VIEW");
                break;
            case "GO BACK TO MAIN":
                view.dispose();
                model.getAm().getMenuController().showMenuView();
                break;
        }
    }

    /**
     * Refreshes all panels, re-attaches listeners, and updates displayed data.
     * Called after any update to the model or view state to ensure UI consistency.
     */
    private void updateView() {
        view.refreshPanels();
        view.setActionListener(this);
    }
}