import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Class: MenuController
 * This class represents the controller of the menu window which it is in menu view.
 * It takes care the of actions when pressed the button and display of the window.
 */
public class MenuController implements ActionListener {
    private MenuView view;
    private AdminModel am = new AdminModel(this); // Only instantiates once

    /**
     * Constructs the MenuController where the model and the view are assigned.
     *
     * @param v The MenuView instance.
     */
    public MenuController(MenuView v) {
        this.view = v;

        view.setActionListener(this);
    }

    /**
     * Handles action events from buttons occurred from the running program.
     *
     * @param e The ActionEvent generated by a user action.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        view.setVisible(false); // Hide window before showing ADMIN/CUSTOMER
        switch (e.getActionCommand()) {
            case "ADMIN":
                AdminView av = new AdminView();
                new AdminController(am, av);
                break;
            case "CUSTOMER":
                CustomerModel cm = new CustomerModel(am);
                CustomerView cv = new CustomerView();
                new CustomerController(cm, cv);
                break;
        }
    }

    /**
     * Setting the visibility of the menu view to be true.
     */
    public void showMenuView() {
        view.setVisible(true);
    }
}